README.md
=> further docs

package.json, src/components/Calendar.vue, src/components/Dropdown.vue, src/components/ObjectForm.vue, src/index.js, src/semantic/components/Popup.vue
- added index file that exports all the functions & components from files explicitly
- initialised component api in vue, in the index file
- lint fixes & lint
=> NPM module fix

README.md, package.json, src/index.js
- Update Readme
- Export mixin
- Update version & npm readme
=> Docs update & export mixin

src/params.js
=> update params for connect

src/params.js, src/utils/watchers.js
this is needed for slower internet connections
=> option to call loadServerJSON with timeout

docs/README.md, docs/sdk-install.md, package.json
- peerDependencies added. If the user does not have that dependencies, NPM will show a warning.
- docs added
=> Peer dependencies

src/app.js, src/config.js
=> windows fixes

CHANGELOG.md, README.md, demo/examples/FilterDropdown.example.vue, docs/components.md, src/components/Checkbox.vue, src/components/FilterDropdown.vue, tests/unit/checkbox.spec.js, tests/unit/filterdropdown.spec.js
- Checkbox updated with new props & events
- A small bug with FilterDropdown fixed
- FilterDropdown now uses built-in checkboxes
=> Checkbox update

src/components/DataTable/table.helpers.js, src/components/ObjectForm.vue, src/components/ObjectFormField.vue
data table support for {{ }} syntax in fields
=> object form optional help text

docs/README.md, docs/config.md, docs/contribute.md, docs/db.md, docs/debug/android.md, docs/debug/ios.md, docs/debug/windows.md, docs/deployment.md, docs/docs.md, docs/events.md, docs/files.md, docs/i18n.md, docs/index.html, docs/params.md, docs/resume.md, docs/state.md, docs/utils.md
Fixes some minor issues, manly typos and letter case issues, and adds better phrasing where possible.
=> Documentation refinements

CHANGELOG.md, src/components/ObjectForm.vue, src/components/ObjectFormField.vue
- ObjectForm now uses Fomantic grid class to plot the fields (customizable as a prop)
- Added compact CSS look to match @elibolonur .’s  look
- Added dash when no value exists in ObjectFormField
=> Adds grid capability in ObjectForm fields

src/components/ObjectFormField.vue
- Fixes dash on empty date values
- Improves value conditionals structure
=> Fixed dash on empty date, improved value conditionals structure.

src/db/sfdcSchema.js
Adds a method to get which field is the name field of an entity object
=> Added method to get an object's name field

src/i18n/date.js, src/i18n/number.js, src/params.js, tests/unit/calendar.spec.js, tests/unit/date.spec.js, tests/unit/number.spec.js
Change in formatting functions (currency, date, decimals and percent) - use account local language
=> Change in formatting functions

package.json, src/components/Dropdown.vue
remove unused logs, click toggle fix
=> dropdown second try

src/index.js, src/validations.js
=> Added validations store

demo/examples/ProgressBar.example.vue, tests/unit/progressbar.spec.js
Alternative colors and increase & decrease buttons added to progress bar
=> Added some features to Progress Bar

src/config.js, src/instance/stores/detailing.store.js
source parameter added to loadConfig
New events to use config for detailing store
=> fix & use config

README.md
https://basecamp.com/2001839/projects/17446436/todos/433755156
This PR adds a simple setup guide.
=> Add simple setup instructions.

CHANGELOG.md, package.json, src/config.js
Added custom caches - field types for `Account`, `Contact` and `User` for the Windows platform
=> Custom caches windows

README.md, stories/welcome.stories.mdx
No related issues
This pull request aims to point out the old SDK is not being developed for new features.
=> docs: Point out the SDK is not being developed for new features.

stories/docs/instance/actions.stories.mdx, stories/docs/instance/detailing-store.stories.mdx
This pull request is for completing documentation for instance action methods
=> feat: missing instance action function documentation added

src/instance/actions/file.js, src/instance/instance.js, src/instance/stores/categories.store.js, src/instance/stores/detailing.store.js, src/instance/stores/files.store.js, src/instance/stores/system.store.js
Instance sore & actions files are reverted with lint rules ignored
=> fix: disable rules for instance files

.github/CODEOWNERS
=> feat: added code owners

src/instance/stores/files.store.js
=> fix: add dash named chapters to chapterless slides

src/components/Dropdown.vue, src/components/ObjectFormField.vue
no link
- adds fullTextSearch param to Dropdown
- adds minSearchItems param to enable control on searchable functionality
=> fix: dropdown - enable full text search, change in searchable params

src/db/query.js
https://pitcher-ag.atlassian.net/browse/APPS-175
https://github.com/PitcherAG/pitcher-ti-web/pull/27
This pull request
=> feat: db error logging on browser console

src/config.js
- Fixes initial config load errors
=> fix: config load

.github/workflows/release-and-publish.yml, release.config.js
=> chore: revert release config

src/components/ObjectForm.vue, src/db/sfdcField.js
no link
Add functionality to make all/single fields to be clearable by default
=> feat: add clearableFields functionality to objectform

release.config.js
Hotfix
Fixes the release branch in release config
=> ci: fix release branch

release.config.js, src/components/ObjectForm.vue
no link
Adds 'fieldChange' emit for ObjectFormField in ObjectForm
=> chore: release

src/db/query.js
https://pitcher-ag.atlassian.net/browse/LAM-270
This pull request fixes an issue where `extraField` data from query would return `null`.
N/A
=> fix: fixed empty extrafield data

src/config.js
=> fix: config store fix

src/config.js
=> fix: fix imports

src/components/Calendar.vue
=> chore: correct typo of the "setting" prop in the watchlist

.github/workflows/release-and-publish.yml
I renamed the tokens and am going to remove their previous ones.
=> ci: update GH and NPM token name

src/components/FilterDropdown.vue
https://pitcher-ag.atlassian.net/browse/APPS-4661
This pull request actually selects all items and not only the visible ones
Added "Before" and "After" screenshots
https://user-images.githubusercontent.com/5673119/177526242-e6f50452-7c5c-41db-b85b-df1ce9a3dbf0.mov
https://user-images.githubusercontent.com/5673119/177526262-e7d4ce25-d01e-428e-a9f7-fee775c3b157.mov
=> fix: "select all" should select all items APPS-4661

src/components/Calendar.vue
https://pitcher-ag.atlassian.net/browse/CAL-2728
=> fix: month and day value is swapped when user enters digit in Date field

.github/CODEOWNERS
https://pitcher-ag.atlassian.net/browse/PLA-8827
This pull request updates the code-owners of vue-sdk. There were only @wojtiku as active code-owner. I've added @AykutBurak and @pegiadise as well (two other admins of the repo).
=> ci: update code-owners [PLA-8827]

src/i18n/i18n.js
https://pitcher-ag.atlassian.net/browse/CORE-139
This pull request fixes the i18n function conflicts happening between vue-sdk & js-platform
=> fix: i18n conflicts with js-platform

src/i18n/i18n.js
This pull request fixes translation conflicts happening between multiple packages. (@pitcher/i18n, vue-i18n etc)
=> fix: translation function conflicts
