src/db/query.js

in ios, account's and contact's extrafield columns are account & contact, but in windows both are Json
There are also JsonUntouched columns but I believe they are same

windows has different columns names for account and contact

---

docs/components.md
src/components/FileCard/FileCard.vue

Use a slot for keywords if given.
In some cases customer may want keywords with different style, ignore some keywords, etc.

use a slot for keywords container

---

CHANGELOG.md
src/components/ObjectForm.vue
stories/components/ObjectForm.stories.mdx

Added capability to make all fields read-only in ObjectForm using an `allFieldsReadOnly` prop.

Read only all ObjectForm feature

---

src/utils/filePath.js

Make sure that the returned path always ends with a slash

Fixed getPitcherFolderPath

---

package.json
stories/docs/sdk-install.stories.mdx

Downgrades `sass-loader` to a compatible version with `webpack@4`. Also updates the `sdk-install` story.

Fix breaking change on sass loader 11

---

src/instance/stores/detailing.store.js

Rollback rule of eqeqeq for detailing store
setCurrentContact method is invoked with (null, null) in iOS but without parameters in windows

fix: rollback eqeqeq rule for detailing store

---

src/components/ObjectForm.vue

no link
If dropdown got only one picklist value and it's controlled by another form field, preselect that value
no screenshots

fix: preselct single picklist value in controlled dropdown

---

src/components/FilterDropdown.vue

None
Revert linter removed returns, causes filterdropdown not to work properly

fix: filter dropdown return emits

---

src/instance/stores/files.store.js

https://pitcher-ag.atlassian.net/browse/PLA-761
- Chapters are now being generated and shown in custom deck items
- ~~Needs edge cases to be checked. See `TODO` @wojtiku added~~ (Mert checked, couldn't find any)
- Needs to be tested on Windows (awaiting update from cagri)
- ~~Needs to be added to `pitcher-js-platform`~~ Done

feat: generate chapters for custom decks when parsing presentations (PLA-761)

---

src/components/Dropdown.vue

no link
- Dropdown: use a unique id for list items keys
- fix issue related to blocked click event by a selected text field

fix: dropdown - use unique id for list items, fix styling issue

---

src/components/NumpadInput.vue

no link
Adds new prop - "allowNegative" which allows having a negative value in the input.

feat: enable negative value in input

---

src/components/ObjectForm.vue
src/db/sfdcField.js

no link
- order form - field required and editable props are now also taken from layout item props. 
- order form - store field validation errors

fix:  read props from layoutitem, add field validati on errors

---

src/components/ObjectForm.vue

no link
When the OrderFormField got some dependent fields, update them only if those are editable.

fix: field should update controlled filed only if not readonly

---

src/components/Calendar.vue

no link
- adds a fix to case, when date was cleared with 'del' or 'backspace' key. 
- change in onSelect event - emit onSelect with params and emit input date change (case when user click same date as previously selected)

fix: emit change when date is cleared with key press

---

src/components/FilterDropdown.vue

no url
- fixes issue related to visible show more button, even if there is no other items to load.

fix: load more btn visibility fix

---

src/components/ObjectForm.vue
src/components/ObjectFormField.vue
tests/unit/gettext.spec.js

no link
- Adds option to enable object form field to be updateable, even if it is blocked in loaded layout

fix: enable manual updateable setting for fields

---

src/components/ObjectForm.vue

no link
Adds 'fieldChange' emit for ObjectFormField in ObjectForm

fix: add fieldchange emit in orderform

---

src/config.js
src/params.js

No issue link as we detected the issue before it was reported.
This pull request makes config load operation much safer.
- Handles the user gathering in config.js via native event, getSFInfo. 
- If the config includes 'userAttrSpecificSettings', config.js requires CRM user information.
- Previously, it was gathered via params.user, and params is empty if it is UI. If it is interactive, this still does not make sense as one should load params before config each time, causing all of the interactives having vue-project-template to fail.
- Makes config.js much more readable.
- Handles an unnecessary console.log removal.
- [ x ] Tested on Windows

Fix/user data gathering core/config, INS-42

---

src/components/ObjectForm.vue
src/components/ObjectFormField.vue

Add property to both ObjectForm and ObjectFormField in order to be able
to call formatCurrency with a second argument (currency)
https://pitcher-ag.atlassian.net/browse/APPS-3654
This pull request adds a new property to ObjectForm and ObjectFormField. The new property is called `forceCurrencyCode` and its purpose is to get all the way to where `formatCurrency` is called (formatCurrency is called when a field of type "currency" exist. Before the fix, formatCurrency was called with just one argument (value) resulting in error when loading an Object wo/ an account (no active call)

feat: add `forceCurrencyCode` property to ObjectForm APPS-3654

---

.github/workflows/release-and-publish.yml

- Replace github and npm secrets with the new organization secrets
- NOTE that **PitcherCI** github user is added to the repo as an Admin (required for admin access)

ci: replace github and npm secrets with organization

---

src/components/NumpadInput.vue

https://pitcher-ag.atlassian.net/browse/APPS-4749
This pull request:
- adds event emission on `focus` and `blur` of the text input inside `NumpadInput`

feat: emit `focus` and `blur` events from `NumpadInput` APPS-4749

---

src/components/FilterDropdown.vue

- https://pitcher-ag.atlassian.net/browse/APPS-5053
- https://pitcher-ag.atlassian.net/browse/APPS-4928
This pull request adds a new optional prop to the FilterDropdown component. 
The `debounceTime` can be set if you need to add a delay between typing and executing the search process
ℹ️ Default input search behaviour is not changed
https://user-images.githubusercontent.com/5673119/189324285-83e30553-8b68-4321-8a56-b5306bd6007a.mov
https://user-images.githubusercontent.com/5673119/189324533-ce0d7ff3-aa32-43ee-a811-e4a087258288.mov

feat: add debounceTime prop for search input APPS-5053
